name: Build and Release on Tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Clone codes
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Cross-compile XueRun with Deno
        run: |
          deno run --allow-read --allow-write --allow-run --allow-env ./tools/bootstrap.ts
          lipo -create -output ./bin/xuerun-universal-apple-darwin ./bin/xuerun-aarch64-apple-darwin ./bin/xuerun-x86_64-apple-darwin
      - name: Generate Message
        run: echo "$(git log -1 --pretty=%s | /bin/cat)" > MESSAGE.txt
      - name: Release Build
        uses: softprops/action-gh-release@v1
        with:
          body_path: MESSAGE.txt
          files: |
            ./bin/xuerun.js
            ./bin/xuerun-x86_64-pc-windows-msvc.exe
            ./bin/xuerun-aarch64-apple-darwin
            ./bin/xuerun-universal-apple-darwin
            ./bin/xuerun-x86_64-unknown-linux-gnu
            ./bin/xuerun-x86_64-apple-darwin
