name: Build and Release on Tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone codes
        uses: action/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Cross-compile XueRun with Deno
        run: deno run --allow-read --allow-write --allow-run --allow-env ./tools/bootstrap.ts
      - name: Generate Message
        run: echo "$(git log -1 --pretty=%s | /bin/cat)" > MESSAGE.txt
      - name: Release Build
        uses: softprops/action-gh-release@v1
        with:
          body_path: MESSAGE.txt
          files: |
            xuerun.js
            xuerun-x86_64-pc-windows-msvc.exe
            xuerun-aarch64-apple-darwin
            xuerun-x86_64-unknown-linux-gnu
            xuerun-x86_64-apple-darwin
